import re

from pyspark.sql import functions as F


# Raw measurement columns available for each sensor event
FIELDS = [f"field_{i}" for i in range(8)]


def _build_aggregation_expressions():
    """
    Define the session-level statistics calculated for each sensor type.

    For every session and sensor type we calculate:
    - number of events
    - session duration
    - mean
    - median
    - standard deviation
    - minimum
    - maximum
    - number of non-null observations

    We also calculate equivalent statistics for the magnitude of
    field_0, field_1 and field_2.
    """

    agg_exprs = [
        F.count("*").alias("n_events"),
        (
            F.max("timestamp") - F.min("timestamp")
        ).alias("duration_ms"),
    ]

    # Statistics for field_0 ... field_7
    for column in FIELDS:
        agg_exprs.extend([
            F.avg(column).alias(f"{column}_mean"),

            F.percentile_approx(
                column,
                0.5
            ).alias(f"{column}_p50"),

            F.stddev(column).alias(f"{column}_std"),

            F.min(column).alias(f"{column}_min"),

            F.max(column).alias(f"{column}_max"),

            F.count(column).alias(f"{column}_nn"),
        ])

    # Statistics for xyz magnitude
    agg_exprs.extend([
        F.avg("mag_012").alias("mag_mean"),

        F.percentile_approx(
            "mag_012",
            0.5
        ).alias("mag_p50"),

        F.stddev("mag_012").alias("mag_std"),

        F.min("mag_012").alias("mag_min"),

        F.max("mag_012").alias("mag_max"),

        F.count("mag_012").alias("mag_nn"),
    ])

    return agg_exprs


def _clean_column_name(column_name):
    """
    Clean column names generated by Spark after pivoting.

    Example:

        1_first(field_0_mean)

    becomes:

        sensor_1_field_0_mean
    """

    match = re.match(
        r"^(\d+)_first\((.+)\)$",
        column_name
    )

    if match:
        sensor, metric = match.groups()

        return f"sensor_{sensor}_{metric}"

    return column_name


def build_session_features(events_df, has_label):
    """
    Transform event-level sensor data into one row per session.

    Parameters
    ----------
    events_df : pyspark.sql.DataFrame
        Raw event-level sensor data.

    has_label : bool
        True for training data, where user_id exists.
        False for test data.

    Returns
    -------
    pyspark.sql.DataFrame
        Session-level feature table.
    """

    # ---------------------------------------------------------
    # 1. Calculate magnitude using field_0, field_1 and field_2
    # ---------------------------------------------------------

    events_with_magnitude = events_df.withColumn(
        "mag_012",
        F.sqrt(
            F.col("field_0") * F.col("field_0")
            + F.col("field_1") * F.col("field_1")
            + F.col("field_2") * F.col("field_2")
        )
    )

    # ---------------------------------------------------------
    # 2. Aggregate events for each session + sensor
    # ---------------------------------------------------------

    agg_exprs = _build_aggregation_expressions()

    session_sensor = (
        events_with_magnitude
        .groupBy(
            "session_id",
            "sensor_type"
        )
        .agg(*agg_exprs)
    )

    # ---------------------------------------------------------
    # 3. Calculate event rate
    # ---------------------------------------------------------

    session_sensor = session_sensor.withColumn(
        "event_rate",
        F.col("n_events")
        / (F.col("duration_ms") + F.lit(1.0))
    )

    # Metrics that will become columns after the pivot
    metric_columns = [
        column
        for column in session_sensor.columns
        if column not in (
            "session_id",
            "sensor_type",
        )
    ]

    # ---------------------------------------------------------
    # 4. Pivot sensor types
    #
    # Before:
    #
    # session | sensor | field_0_mean
    #   A     |   1    |  ...
    #   A     |   2    |  ...
    #
    # After:
    #
    # session | sensor_1_field_0_mean | sensor_2_field_0_mean
    #   A     |          ...          |         ...
    # ---------------------------------------------------------

    wide = (
        session_sensor
        .groupBy("session_id")
        .pivot("sensor_type")
        .agg(
            *[
                F.first(column)
                for column in metric_columns
            ]
        )
    )

    # ---------------------------------------------------------
    # 5. Clean Spark-generated pivot column names
    # ---------------------------------------------------------

    for column in wide.columns:
        new_name = _clean_column_name(column)

        if new_name != column:
            wide = wide.withColumnRenamed(
                column,
                new_name
            )

    # ---------------------------------------------------------
    # 6. Add target label for training data
    # ---------------------------------------------------------

    if has_label:

        labels = (
            events_with_magnitude
            .select(
                "session_id",
                "user_id"
            )
            .distinct()
        )

        wide = wide.join(
            labels,
            on="session_id",
            how="left"
        )

    return wide


def align_train_test_features(
    train_features,
    test_features,
):
    """
    Ensure train and test feature tables contain exactly
    the same feature columns and in the same order.

    Missing features are added as null values and then
    filled with zero.

    Parameters
    ----------
    train_features : pyspark.sql.DataFrame
        Training session features including user_id.

    test_features : pyspark.sql.DataFrame
        Test session features without user_id.

    Returns
    -------
    tuple
        (
            aligned_train_features,
            aligned_test_features,
            feature_columns
        )
    """

    train_columns = (
        set(train_features.columns)
        - {"user_id"}
    )

    test_columns = set(
        test_features.columns
    )

    # Union of features appearing in train or test
    all_feature_columns = sorted(
        (
            train_columns
            | test_columns
        )
        - {"session_id"}
    )

    # ---------------------------------------------------------
    # Add features missing from either train or test
    # ---------------------------------------------------------

    for column in all_feature_columns:

        if column not in train_features.columns:
            train_features = (
                train_features.withColumn(
                    column,
                    F.lit(None).cast("double")
                )
            )

        if column not in test_features.columns:
            test_features = (
                test_features.withColumn(
                    column,
                    F.lit(None).cast("double")
                )
            )

    # ---------------------------------------------------------
    # Force identical feature order
    # ---------------------------------------------------------

    train_features = (
        train_features
        .select(
            ["session_id"]
            + all_feature_columns
            + ["user_id"]
        )
        .fillna(0)
    )

    test_features = (
        test_features
        .select(
            ["session_id"]
            + all_feature_columns
        )
        .fillna(0)
    )

    return (
        train_features,
        test_features,
        all_feature_columns,
    )